--
-- PostgreSQL database dump
--

\restrict gxGoL6dxZOQ9lVm7dpWWggnW88vNOsVUvfhbRVtPSNDlncPqmQNJaQj0z3IGB8w

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_logs (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    target_model character varying(50) NOT NULL,
    target_id integer,
    description text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    ip_address inet,
    user_id bigint,
    CONSTRAINT admin_logs_target_id_check CHECK ((target_id >= 0))
);


ALTER TABLE public.admin_logs OWNER TO postgres;

--
-- Name: admin_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    selected_size character varying(10) NOT NULL,
    CONSTRAINT cart_items_product_id_check CHECK ((product_id >= 0)),
    CONSTRAINT cart_items_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_items OWNER TO postgres;

--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    product_id integer NOT NULL,
    product_name character varying(255) NOT NULL,
    product_image character varying(1000) NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    shoe_size character varying(10) NOT NULL,
    product_unit character varying(10) NOT NULL,
    product_unit_value numeric(10,3) NOT NULL,
    CONSTRAINT order_items_product_id_check CHECK ((product_id >= 0)),
    CONSTRAINT order_items_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    order_number character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    shipping_name character varying(200) NOT NULL,
    shipping_email character varying(254) NOT NULL,
    shipping_phone character varying(20) NOT NULL,
    shipping_address text NOT NULL,
    shipping_city character varying(100) NOT NULL,
    shipping_pincode character varying(10) NOT NULL,
    shipping_state character varying(100) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    short_description character varying(500) NOT NULL,
    price numeric(10,2) NOT NULL,
    category character varying(100) NOT NULL,
    brand character varying(100) NOT NULL,
    product_code character varying(100) NOT NULL,
    image_url character varying(1000) NOT NULL,
    gallery_urls jsonb NOT NULL,
    features jsonb NOT NULL,
    stock integer NOT NULL,
    rating numeric(3,1) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    size_stock jsonb NOT NULL,
    unit character varying(10) NOT NULL,
    unit_value numeric(10,3) NOT NULL,
    discount_percent smallint NOT NULL,
    CONSTRAINT products_discount_percent_check CHECK ((discount_percent >= 0)),
    CONSTRAINT products_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    email_verification_code character varying(6) NOT NULL,
    email_verification_expires_at timestamp with time zone,
    email_verified boolean NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO postgres;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist_items (
    id bigint NOT NULL,
    product_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT wishlist_items_product_id_check CHECK ((product_id >= 0))
);


ALTER TABLE public.wishlist_items OWNER TO postgres;

--
-- Name: wishlist_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admin_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin_logs (id, action, target_model, target_id, description, "timestamp", ip_address, user_id) FROM stdin;
1	product_create	Product	1	Created product: Ghee (ID: None)	2026-04-07 21:14:48.81756+05:30	127.0.0.1	1
2	product_update	Product	1	Updated product: Ghee (ID: 1)	2026-04-07 21:21:56.112698+05:30	127.0.0.1	1
3	product_update	Product	1	Updated product: Ghee (ID: 1)	2026-04-07 21:27:19.666963+05:30	127.0.0.1	1
4	product_update	Product	1	Updated product: Ghee (ID: 1)	2026-04-07 22:11:24.019026+05:30	127.0.0.1	1
5	product_update	Product	1	Updated product: Ghee (ID: 1)	2026-04-07 22:11:40.126117+05:30	127.0.0.1	1
6	product_create	Product	2	Created product: Butter (ID: None)	2026-04-07 22:46:02.799933+05:30	192.168.29.143	1
7	product_create	Product	3	Created product: Khoa (ID: None)	2026-04-07 22:46:28.175882+05:30	192.168.29.143	1
8	product_create	Product	4	Created product: Paneer (ID: None)	2026-04-07 22:46:52.830389+05:30	192.168.29.143	1
9	product_create	Product	5	Created product: Pedha (ID: None)	2026-04-07 22:47:50.756348+05:30	192.168.29.143	1
10	product_create	Product	6	Created product: Modak (ID: None)	2026-04-07 22:48:13.980115+05:30	192.168.29.143	1
11	product_create	Product	1	Created product: Ghee (ID: None)	2026-04-08 20:43:24.361653+05:30	127.0.0.1	1
12	product_update	Product	1	Updated product: Ghee (ID: 1)	2026-04-13 14:13:01.38788+05:30	127.0.0.1	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add cart item	7	add_cartitem
26	Can change cart item	7	change_cartitem
27	Can delete cart item	7	delete_cartitem
28	Can view cart item	7	view_cartitem
29	Can add wishlist item	8	add_wishlistitem
30	Can change wishlist item	8	change_wishlistitem
31	Can delete wishlist item	8	delete_wishlistitem
32	Can view wishlist item	8	view_wishlistitem
33	Can add product	9	add_product
34	Can change product	9	change_product
35	Can delete product	9	delete_product
36	Can view product	9	view_product
37	Can add order	11	add_order
38	Can change order	11	change_order
39	Can delete order	11	delete_order
40	Can view order	11	view_order
41	Can add order item	12	add_orderitem
42	Can change order item	12	change_orderitem
43	Can delete order item	12	delete_orderitem
44	Can view order item	12	view_orderitem
45	Can add admin log	10	add_adminlog
46	Can change admin log	10	change_adminlog
47	Can delete admin log	10	delete_adminlog
48	Can view admin log	10	view_adminlog
\.


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_items (id, product_id, quantity, created_at, user_id, selected_size) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-07 21:14:48.83515+05:30	1	Ghee	1	[{"added": {}}]	9	1
2	2026-04-07 21:21:56.118408+05:30	1	Ghee	2	[{"changed": {"fields": ["Discount percent"]}}]	9	1
3	2026-04-07 21:27:19.680608+05:30	1	Ghee	2	[{"changed": {"fields": ["Price"]}}]	9	1
4	2026-04-07 21:50:04.52227+05:30	1	ORD177557810877CB43A (a@mail.com)	2	[{"deleted": {"name": "order item", "object": "Ghee [1.000 l] x1"}}]	11	1
5	2026-04-07 21:50:22.262005+05:30	1	ORD177557810877CB43A (a@mail.com)	2	[{"added": {"name": "order item", "object": "Ghee [1 pc] x1"}}]	11	1
6	2026-04-07 21:50:44.060023+05:30	1	ORD177557810877CB43A (a@mail.com)	2	[{"changed": {"fields": ["Status"]}}]	11	1
7	2026-04-07 22:11:24.0234+05:30	1	Ghee	2	[{"changed": {"fields": ["Image url"]}}]	9	1
8	2026-04-07 22:11:40.128526+05:30	1	Ghee	2	[{"changed": {"fields": ["Gallery urls"]}}]	9	1
9	2026-04-07 22:46:02.80515+05:30	2	Butter	1	[{"added": {}}]	9	1
10	2026-04-07 22:46:28.179171+05:30	3	Khoa	1	[{"added": {}}]	9	1
11	2026-04-07 22:46:52.833469+05:30	4	Paneer	1	[{"added": {}}]	9	1
12	2026-04-07 22:47:50.760851+05:30	5	Pedha	1	[{"added": {}}]	9	1
13	2026-04-07 22:48:13.984001+05:30	6	Modak	1	[{"added": {}}]	9	1
14	2026-04-08 20:43:24.389234+05:30	1	Ghee	1	[{"added": {}}]	9	1
15	2026-04-13 14:13:01.422386+05:30	1	Ghee	2	[{"changed": {"fields": ["Stock"]}}]	9	1
16	2026-04-13 14:25:08.542305+05:30	2	ORDACCD36C (a@mail.com)	3		11	1
17	2026-04-13 14:25:08.542362+05:30	1	ORD177557810877CB43A (a@mail.com)	3		11	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	cart	cartitem
8	wishlist	wishlistitem
9	products	product
10	orders	adminlog
11	orders	order
12	orders	orderitem
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-07 03:23:02.896859+05:30
2	contenttypes	0002_remove_content_type_name	2026-04-07 03:23:02.916214+05:30
3	auth	0001_initial	2026-04-07 03:23:03.003917+05:30
4	auth	0002_alter_permission_name_max_length	2026-04-07 03:23:03.013159+05:30
5	auth	0003_alter_user_email_max_length	2026-04-07 03:23:03.021941+05:30
6	auth	0004_alter_user_username_opts	2026-04-07 03:23:03.031818+05:30
7	auth	0005_alter_user_last_login_null	2026-04-07 03:23:03.041721+05:30
8	auth	0006_require_contenttypes_0002	2026-04-07 03:23:03.044417+05:30
9	auth	0007_alter_validators_add_error_messages	2026-04-07 03:23:03.053259+05:30
10	auth	0008_alter_user_username_max_length	2026-04-07 03:23:03.063532+05:30
11	auth	0009_alter_user_last_name_max_length	2026-04-07 03:23:03.073489+05:30
12	auth	0010_alter_group_name_max_length	2026-04-07 03:23:03.087169+05:30
13	auth	0011_update_proxy_permissions	2026-04-07 03:23:03.10115+05:30
14	auth	0012_alter_user_first_name_max_length	2026-04-07 03:23:03.112822+05:30
15	accounts	0001_initial	2026-04-07 03:23:03.181146+05:30
16	accounts	0002_user_email_verification_code_and_more	2026-04-07 03:23:03.225016+05:30
17	admin	0001_initial	2026-04-07 03:23:03.260437+05:30
18	admin	0002_logentry_remove_auto_add	2026-04-07 03:23:03.283903+05:30
19	admin	0003_logentry_add_action_flag_choices	2026-04-07 03:23:03.297756+05:30
20	cart	0001_initial	2026-04-07 03:23:03.330225+05:30
21	cart	0002_cartitem_cart_items_user_id_fe143f_idx_and_more	2026-04-07 03:23:03.364749+05:30
22	cart	0003_cartitem_selected_size	2026-04-07 03:23:03.382196+05:30
23	cart	0004_normalize_selected_size	2026-04-07 03:23:03.419656+05:30
24	orders	0001_initial	2026-04-07 03:23:03.500604+05:30
25	orders	0002_order_orders_user_id_51663a_idx_and_more	2026-04-07 03:23:03.594766+05:30
26	orders	0003_orderitem_shoe_size	2026-04-07 03:23:03.621443+05:30
27	orders	0004_adminlog	2026-04-07 03:23:03.739458+05:30
28	orders	0005_rename_admin_logs_user_id_0e1821_idx_admin_logs_user_id_916751_idx_and_more	2026-04-07 03:23:03.796744+05:30
29	orders	0006_alter_order_shipping_email_and_more	2026-04-07 03:23:03.966818+05:30
30	orders	0007_orderitem_product_unit_orderitem_product_unit_value	2026-04-07 03:23:03.997599+05:30
31	products	0001_initial	2026-04-07 03:23:04.013062+05:30
32	products	0002_alter_product_brand_alter_product_category_and_more	2026-04-07 03:23:04.07423+05:30
33	products	0003_product_size_stock	2026-04-07 03:23:04.089052+05:30
34	products	0004_product_unit_product_unit_value	2026-04-07 03:23:04.104308+05:30
35	sessions	0001_initial	2026-04-07 03:23:04.122585+05:30
36	wishlist	0001_initial	2026-04-07 03:23:04.17133+05:30
37	wishlist	0002_wishlistitem_wishlist_it_user_id_b5f68a_idx_and_more	2026-04-07 03:23:04.227184+05:30
38	products	0005_product_discount_percent	2026-04-07 21:20:47.261166+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
oergkxojni3w5pcir22a6tqfykkp6aql	.eJxVjEEOwiAQRe_C2pCWAVpcuvcMzcwwSNVAUtqV8e7apAvd_vfef6kJtzVPW5NlmqM6q16dfjdCfkjZQbxjuVXNtazLTHpX9EGbvtYoz8vh_h1kbPlb22QsEgcrbIGYGEwPvkfhwYxjcklE7OCCAwZB8YMHIuDkAnRjF0G9PwEeOGM:1wA8b3:DaB-L4uPaBQ8-fE_V4ZBtb_iNFHYxgxklVGBS6tbd_w	2026-04-21 21:14:09.844949+05:30
haurjngaexaa4qp1rtyzde3o6fbz1en5	.eJxVjEEOwiAQRe_C2pCWAVpcuvcMzcwwSNVAUtqV8e7apAvd_vfef6kJtzVPW5NlmqM6q16dfjdCfkjZQbxjuVXNtazLTHpX9EGbvtYoz8vh_h1kbPlb22QsEgcrbIGYGEwPvkfhwYxjcklE7OCCAwZB8YMHIuDkAnRjF0G9PwEeOGM:1wA9Tr:Wmgm6ol2KFFJ2ZwQa9NjkexSQimreELq5fqMcBZk5s4	2026-04-21 22:10:47.469927+05:30
khwspwkitcvhx4fbnze75vg7j120zhr0	.eJxVjEEOwiAQRe_C2pCWAVpcuvcMzcwwSNVAUtqV8e7apAvd_vfef6kJtzVPW5NlmqM6q16dfjdCfkjZQbxjuVXNtazLTHpX9EGbvtYoz8vh_h1kbPlb22QsEgcrbIGYGEwPvkfhwYxjcklE7OCCAwZB8YMHIuDkAnRjF0G9PwEeOGM:1wAA0z:TwXA7gMFu7JpF0gEyGkP_CvjioaU8TJJSUuNf66vQ-o	2026-04-21 22:45:01.735852+05:30
l39vnlxnkleq0dghgqes054e04uaiqm6	.eJxVjEEOwiAQRe_C2pCWAVpcuvcMzcwwSNVAUtqV8e7apAvd_vfef6kJtzVPW5NlmqM6q16dfjdCfkjZQbxjuVXNtazLTHpX9EGbvtYoz8vh_h1kbPlb22QsEgcrbIGYGEwPvkfhwYxjcklE7OCCAwZB8YMHIuDkAnRjF0G9PwEeOGM:1wAUaI:YTav-7BOqGrAGG6Kbx-yq7gOg6X-GpVrJMMQYNC16ys	2026-04-22 20:42:50.810921+05:30
vacxazj2slvo59ko1ixxv0ik61cj6rc5	.eJxVjEEOwiAQRe_C2pCWAVpcuvcMzcwwSNVAUtqV8e7apAvd_vfef6kJtzVPW5NlmqM6q16dfjdCfkjZQbxjuVXNtazLTHpX9EGbvtYoz8vh_h1kbPlb22QsEgcrbIGYGEwPvkfhwYxjcklE7OCCAwZB8YMHIuDkAnRjF0G9PwEeOGM:1wCCsY:ptzABJUJIXsP_ml34Ysh0l7jOkjWoHysPAI0LoTyxeA	2026-04-27 14:12:46.768641+05:30
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, product_id, product_name, product_image, price, quantity, order_id, shoe_size, product_unit, product_unit_value) FROM stdin;
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, order_number, status, total_amount, shipping_name, shipping_email, shipping_phone, shipping_address, shipping_city, shipping_pincode, shipping_state, notes, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, description, short_description, price, category, brand, product_code, image_url, gallery_urls, features, stock, rating, is_active, created_at, updated_at, size_stock, unit, unit_value, discount_percent) FROM stdin;
1	Ghee			123.00					[]	[]	0	0.0	t	2026-04-08 20:43:24.35736+05:30	2026-04-13 14:13:57.288974+05:30	{}	pc	1.000	0
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, last_login, is_superuser, name, email, is_active, is_staff, created_at, email_verification_code, email_verification_expires_at, email_verified) FROM stdin;
2	pbkdf2_sha256$1200000$njF0YdEVRzGnDC56qNUELP$UK7zch7CfAaW2k6QnX2XEPU9e2xNk4H/0oq/82bAZ/o=	\N	f	User	a@mail.com	t	f	2026-04-07 21:37:58.138328+05:30		\N	t
1	pbkdf2_sha256$1200000$pQNIccqNZ6hurmULuRKuO6$akHwfLZE7QW0Z5GzH6xjMgAIpFUqOCJpPpG56nsmTEk=	2026-04-13 14:12:46.759389+05:30	t	A	test@user.com	t	t	2026-04-07 21:13:52.539384+05:30		\N	f
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: wishlist_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wishlist_items (id, product_id, created_at, user_id) FROM stdin;
\.


--
-- Name: admin_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_logs_id_seq', 12, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 2, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 17, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 38, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_id_seq', 3, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 2, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- Name: wishlist_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wishlist_items_id_seq', 1, false);


--
-- Name: admin_logs admin_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_logs
    ADD CONSTRAINT admin_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_user_id_product_id_e4319647_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_user_id_product_id_e4319647_uniq UNIQUE (user_id, product_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_order_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_order_number_key UNIQUE (order_number);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: wishlist_items wishlist_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT wishlist_items_pkey PRIMARY KEY (id);


--
-- Name: wishlist_items wishlist_items_user_id_product_id_258ffff0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT wishlist_items_user_id_product_id_258ffff0_uniq UNIQUE (user_id, product_id);


--
-- Name: admin_logs_action_cc36f2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX admin_logs_action_cc36f2_idx ON public.admin_logs USING btree (action, "timestamp");


--
-- Name: admin_logs_target__42fc56_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX admin_logs_target__42fc56_idx ON public.admin_logs USING btree (target_model, target_id);


--
-- Name: admin_logs_user_id_7cc6dd52; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX admin_logs_user_id_7cc6dd52 ON public.admin_logs USING btree (user_id);


--
-- Name: admin_logs_user_id_916751_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX admin_logs_user_id_916751_idx ON public.admin_logs USING btree (user_id, "timestamp");


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: cart_items_product_6a1de7_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_items_product_6a1de7_idx ON public.cart_items USING btree (product_id);


--
-- Name: cart_items_user_id_74745f54; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_items_user_id_74745f54 ON public.cart_items USING btree (user_id);


--
-- Name: cart_items_user_id_fe143f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_items_user_id_fe143f_idx ON public.cart_items USING btree (user_id, created_at);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: order_items_order_i_26ad88_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_order_i_26ad88_idx ON public.order_items USING btree (order_id);


--
-- Name: order_items_order_id_412ad78b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_order_id_412ad78b ON public.order_items USING btree (order_id);


--
-- Name: order_items_product_a53db1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_product_a53db1_idx ON public.order_items USING btree (product_id);


--
-- Name: orders_order_number_fdca857f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_number_fdca857f_like ON public.orders USING btree (order_number varchar_pattern_ops);


--
-- Name: orders_shipping_email_52f06393; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_shipping_email_52f06393 ON public.orders USING btree (shipping_email);


--
-- Name: orders_shipping_email_52f06393_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_shipping_email_52f06393_like ON public.orders USING btree (shipping_email varchar_pattern_ops);


--
-- Name: orders_shipping_phone_4cf45ec5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_shipping_phone_4cf45ec5 ON public.orders USING btree (shipping_phone);


--
-- Name: orders_shipping_phone_4cf45ec5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_shipping_phone_4cf45ec5_like ON public.orders USING btree (shipping_phone varchar_pattern_ops);


--
-- Name: orders_status_11db6c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_status_11db6c_idx ON public.orders USING btree (status, created_at);


--
-- Name: orders_user_id_17dbdf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_user_id_17dbdf_idx ON public.orders USING btree (user_id, status);


--
-- Name: orders_user_id_51663a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_user_id_51663a_idx ON public.orders USING btree (user_id, created_at);


--
-- Name: orders_user_id_7e2523fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_user_id_7e2523fb ON public.orders USING btree (user_id);


--
-- Name: products_brand_d3f3629a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_brand_d3f3629a ON public.products USING btree (brand);


--
-- Name: products_brand_d3f3629a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_brand_d3f3629a_like ON public.products USING btree (brand varchar_pattern_ops);


--
-- Name: products_category_ed47a042; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_category_ed47a042 ON public.products USING btree (category);


--
-- Name: products_category_ed47a042_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_category_ed47a042_like ON public.products USING btree (category varchar_pattern_ops);


--
-- Name: products_is_acti_08ec1e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_is_acti_08ec1e_idx ON public.products USING btree (is_active, category);


--
-- Name: products_is_acti_c9c3a3_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_is_acti_c9c3a3_idx ON public.products USING btree (is_active, brand);


--
-- Name: products_is_acti_d5bdcf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_is_acti_d5bdcf_idx ON public.products USING btree (is_active, created_at);


--
-- Name: products_is_active_4d0bbafa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_is_active_4d0bbafa ON public.products USING btree (is_active);


--
-- Name: products_product_code_de3ca32c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_code_de3ca32c ON public.products USING btree (product_code);


--
-- Name: products_product_code_de3ca32c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_code_de3ca32c_like ON public.products USING btree (product_code varchar_pattern_ops);


--
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (email varchar_pattern_ops);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: wishlist_it_product_282ecb_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_it_product_282ecb_idx ON public.wishlist_items USING btree (product_id);


--
-- Name: wishlist_it_user_id_b5f68a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_it_user_id_b5f68a_idx ON public.wishlist_items USING btree (user_id, created_at);


--
-- Name: wishlist_items_user_id_fb64a501; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_items_user_id_fb64a501 ON public.wishlist_items USING btree (user_id);


--
-- Name: admin_logs admin_logs_user_id_7cc6dd52_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_logs
    ADD CONSTRAINT admin_logs_user_id_7cc6dd52_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_items cart_items_user_id_74745f54_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_user_id_74745f54_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_items order_items_order_id_412ad78b_fk_orders_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_412ad78b_fk_orders_id FOREIGN KEY (order_id) REFERENCES public.orders(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders orders_user_id_7e2523fb_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_user_id_7e2523fb_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_items wishlist_items_user_id_fb64a501_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT wishlist_items_user_id_fb64a501_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict gxGoL6dxZOQ9lVm7dpWWggnW88vNOsVUvfhbRVtPSNDlncPqmQNJaQj0z3IGB8w

