# Generated by Django 6.0.3 on 2026-03-20 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["user", "created_at"], name="cart_items_user_id_fe143f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product_id"], name="cart_items_product_6a1de7_idx"
            ),
        ),
    ]
