# Generated by Django 6.0.3 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_cart_items_user_id_fe143f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="selected_size",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
