# Generated by Django 6.0.3 on 2026-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_brand_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size_stock",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
