# Generated by Django 6.0.3 on 2026-04-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_size_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("ml", "ml"),
                    ("l", "L"),
                    ("g", "g"),
                    ("kg", "kg"),
                    ("pc", "piece"),
                ],
                default="pc",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_value",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
