# Generated by Django 6.0.3 on 2026-03-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_adminlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminlog",
            new_name="admin_logs_user_id_916751_idx",
            old_name="admin_logs_user_id_0e1821_idx",
        ),
        migrations.RenameIndex(
            model_name="adminlog",
            new_name="admin_logs_action_cc36f2_idx",
            old_name="admin_logs_action_15c41c_idx",
        ),
        migrations.RenameIndex(
            model_name="adminlog",
            new_name="admin_logs_target__42fc56_idx",
            old_name="admin_logs_target__bdb4cb_idx",
        ),
    ]
