# Generated by Django 6.0.3 on 2026-04-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_shipping_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_unit",
            field=models.CharField(blank=True, default="pc", max_length=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_unit_value",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
