# Generated by Django 6.0.3 on 2026-03-20 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["user", "created_at"], name="wishlist_it_user_id_b5f68a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["product_id"], name="wishlist_it_product_282ecb_idx"
            ),
        ),
    ]
